FROM fedora:41

# Raggruppa le installazioni
RUN dnf update -y && \
    dnf install -y \
        git \
        gcc \
        gfortran \
        fastfetch \
        xterm \
        xclock \
        xhost \
        xauth \
        hostname \
        glibc-langpack-en \
        libX11-devel \
        motif-devel \
        sqlite-devel \
        libbsd-devel \
        tcl tk tix \
        ncurses-devel \
        leafpad \
        gdbm-devel \
        ksh \
        which \
        sudo \
        ps \
        passwd \
        cpio \
        shadow-utils && \
    dnf clean all

# Imposta le localizzazioni di base
ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LANGUAGE=en_US:en

# Crea le directory e copia i file
RUN mkdir -p /home/legoroot_fedora41
COPY /LegoPST /home/legoroot_fedora41
WORKDIR /home/legoroot_fedora41/gdbm-install
RUN make -f Makefile.mk

# Configura sudoers per permettere creazione utenti dinamici
RUN echo '%wheel ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    mkdir -p /etc/sudoers.d

# Directory di lavoro di default
WORKDIR /root

# Comando di default
CMD ["tail","-f","/dev/null"]

