# demo_nuclear.conf - cosa entra nella demo 'nuclear' (make_demo_tgz.sh -d nuclear)
AMMESSE_RADICE="legocad sked"
AMMESSE_LEGOCAD="legopc_prefs.tcl PWRN1PSS SLB1_NI2 catalogo_xstaz libgraph libut libut_bin libut_mmi libut_reg r_SLB1_0"
AMMESSE_SKED="SLaurent_0"
